version: "3.8"
services:
  lead_score:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../lead_score/utils/:/app/lead_score/utils/  # Debug
      - ../lead_score/data/:/app/lead_score/data:rw  # Debug
      - ../lead_score/models/:/app/lead_score/models:rw # Debug
      - ../lead_score/app.py:/app/lead_score/app.py  # Debug
    ports:
      - "5001:5001"
    env_file:
      ./.env